frompicamera2.encodersimportH264Encoder
frompicamera2importPicamera2
importtime
picam2=Picamera2()
video_config=picam2.create_video_configuration()
picam2.configure(video_config)
encoder=H264Encoder(bitrate=10000000)
output="test.h264"
picam2.start_recording(encoder,'test.h264',quality=Quality.HIGH)
